-- SUPABASE MIGRATION 082 — JUDGE TOKEN REGENERATION & REVOCATION SUPPORT
-- Enables force-refresh option for regenerating judge access codes and QR codes

BEGIN;

CREATE OR REPLACE FUNCTION public.generate_judge_token(
  p_judge_id UUID,
  p_schedule_id UUID,
  p_tenant_id UUID,
  p_created_by UUID DEFAULT NULL,
  p_force_refresh BOOLEAN DEFAULT false
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_token TEXT;
  v_token_hash TEXT;
  v_existing_token TEXT;
BEGIN
  -- If force refresh is NOT requested, check if a valid, active token already exists
  IF NOT p_force_refresh THEN
    SELECT token INTO v_existing_token
    FROM public.judge_tokens
    WHERE judge_id = p_judge_id
      AND schedule_id = p_schedule_id
      AND tenant_id = p_tenant_id
      AND (is_revoked IS NOT TRUE)
      AND (expires_at IS NULL OR expires_at > NOW())
      AND is_used = false
    ORDER BY created_at DESC
    LIMIT 1;

    IF v_existing_token IS NOT NULL THEN
      RETURN v_existing_token;
    END IF;
  ELSE
    -- If force refresh is requested, revoke all existing active tokens for this judge & schedule
    UPDATE public.judge_tokens
    SET is_revoked = true,
        revoked_at = NOW(),
        revoked_by = p_created_by,
        revocation_reason = 'Regenerated by administrator'
    WHERE judge_id = p_judge_id
      AND schedule_id = p_schedule_id
      AND tenant_id = p_tenant_id
      AND (is_revoked IS NOT TRUE);
  END IF;

  -- Generate a new unique 6-character hex token
  v_token := upper(encode(extensions.gen_random_bytes(3), 'hex'));
  v_token_hash := encode(digest(upper(trim(v_token)), 'sha256'), 'hex');

  INSERT INTO public.judge_tokens (
    judge_id,
    schedule_id,
    tenant_id,
    created_by,
    token,
    token_hash,
    created_at,
    is_used,
    is_revoked
  ) VALUES (
    p_judge_id,
    p_schedule_id,
    p_tenant_id,
    COALESCE(p_created_by, gen_random_uuid()),
    v_token,
    v_token_hash,
    now(),
    false,
    false
  );

  RETURN v_token;
END;
$$;

GRANT EXECUTE ON FUNCTION public.generate_judge_token(UUID, UUID, UUID, UUID, BOOLEAN) TO authenticated, anon;

COMMIT;
